In [1]:
import pandas as pd
import numpy as np

In [9]:
fc = pd.read_csv("dish_feature_contribute.csv")
fc
# fc = fc.T
# fc

,Unnamed: 0,Dim.1,Dim.2,Dim.3,Dim.4,Dim.5,Dim.6,Dim.7,Dim.8
0,Calories.kcal.,17.581663,2.981759,2.336028,0.001882,0.047302,1.436760,0.721120,0.064907
1,Moisture.g.,6.454732,1.178606,22.342327,1.386630,0.662240,0.097797,8.347840,0.567982
2,Protein.g.,6.780186,2.637601,6.877935,16.887248,9.980813,2.057991,11.855172,1.418381
3,Saturated_fat.g.,11.752230,11.052743,0.810378,4.921544,4.338512,1.199058,5.213293,0.003242
4,Carbohydrate.g.,4.109680,0.001264,38.974734,0.062207,0.610771,1.972570,3.006303,0.003415
5,Dietary_fiber.g.,2.970793,18.976366,3.035275,5.179627,2.758626,1.646086,8.501307,24.697162
6,Mg.mg.,9.293294,12.630615,0.001477,0.042359,0.741304,6.061938,1.204585,6.238856
7,Fe.mg.,3.879644,13.592696,0.109081,2.629127,1.408883,23.600047,0.007745,50.300945
8,Zn.mg.,7.165489,6.631528,6.391491,6.481095,12.928927,0.080274,0.630565,7.391256
9,VitaminA.IU.,0.118615,1.093012,4.126997,55.399013,1.363428,6.718172,30.277335,0.204182
10,VitaminB_group,1.844821,12.969902,0.121333,0.550328,1.196471,46.897272,22.287353,9.003481
11,Fatty_acid_S.mg.,11.750105,11.055919,0.812430,4.913444,4.338486,1.178046,5.250099,0.001930
12,Fatty_acid_M.mg.,11.284971,5.058161,7.549648,0.109402,4.890685,0.054259,0.834264,0.084401
13,Fatty_acid_P.mg.,5.013776,0.139828,6.510866,1.436094,54.733551,6.999730,1.863019,0.019861

In [3]:
# fc.set_index(['Unnamed'])
t = fc[1:]
t = t/100
t = round(t,3)
nu_dim = np.array(t)
t

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
Dim.1,0.175817,0.0645473,0.0678019,0.117522,0.0410968,0.0297079,0.0929329,0.0387964,0.0716549,0.00118615,0.0184482,0.117501,0.11285,0.0501378
Dim.2,0.0298176,0.0117861,0.026376,0.110527,1.26447e-05,0.189764,0.126306,0.135927,0.0663153,0.0109301,0.129699,0.110559,0.0505816,0.00139828
Dim.3,0.0233603,0.223423,0.0687794,0.00810378,0.389747,0.0303528,1.47653e-05,0.00109081,0.0639149,0.04127,0.00121333,0.0081243,0.0754965,0.0651087
Dim.4,1.88188e-05,0.0138663,0.168872,0.0492154,0.00062207,0.0517963,0.000423593,0.0262913,0.0648109,0.55399,0.00550328,0.0491344,0.00109402,0.0143609
Dim.5,0.000473021,0.0066224,0.0998081,0.0433851,0.00610771,0.0275863,0.00741304,0.0140888,0.129289,0.0136343,0.0119647,0.0433849,0.0489068,0.547336
Dim.6,0.0143676,0.000977975,0.0205799,0.0119906,0.0197257,0.0164609,0.0606194,0.236,0.000802744,0.0671817,0.468973,0.0117805,0.000542587,0.0699973
Dim.7,0.0072112,0.0834784,0.118552,0.0521329,0.030063,0.0850131,0.0120458,7.7453e-05,0.00630565,0.302773,0.222874,0.052501,0.00834264,0.0186302
Dim.8,0.00064907,0.00567982,0.0141838,3.24151e-05,3.41458e-05,0.246972,0.0623886,0.503009,0.0739126,0.00204182,0.0900348,1.93018e-05,0.000844012,0.000198611

In [4]:
# fi = pd.read_csv("dish_feature_importance.csv")
# fi.head()

In [5]:
result = pd.read_csv("dish_kMeans_result7.csv")
newResult=result[['median_A1','median_A2','median_A3','median_A4','median_A5','median_A6','median_A7','median_A8']]
newResult

,median_A1,median_A2,median_A3,median_A4,median_A5,median_A6,median_A7,median_A8
0,0.005810,0.223051,1.464952,-0.398734,-0.038313,0.260216,0.407896,-0.148401
1,4.353202,-5.591580,0.633949,1.838636,-1.330396,-4.857299,0.432942,-4.321270
2,0.420135,-0.043172,-1.322020,-0.744851,0.433003,0.041623,0.225447,-0.138565
3,4.152073,-2.926090,0.034281,-0.304881,-0.989382,0.291214,0.017594,1.087258
4,2.908019,1.910431,0.462431,0.793715,0.606389,-0.077535,-0.474052,-0.102391
5,-1.565644,-0.715507,-1.249124,2.573093,0.251958,0.705150,1.438314,0.318750
6,-1.692518,-0.042077,-0.257271,-0.009690,-0.151742,-0.254999,-0.358675,0.119780

In [6]:
cluster_nutrition = newResult.dot(nu_dim)
cluster_nutrition

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.0484521,0.357988,0.0874837,0.0403018,0.588111,0.067564,0.0397104,0.00791429,0.0698567,-0.0178345,0.227743,0.0404685,0.123646,0.0950723
1,0.543382,0.380255,0.259056,-0.104329,0.335984,-1.96436,-0.869598,-3.8808,-0.391768,0.766595,-3.22046,-0.103498,0.190563,-0.782842
2,0.0440213,-0.258147,-0.12053,0.0282656,-0.488213,-0.0768442,0.0330603,-0.0643521,-0.0583336,-0.390497,0.0589196,0.0283645,-0.0324311,0.168316
3,0.648098,0.238326,0.0799635,0.111341,0.184039,-0.199149,0.0945157,0.357062,0.0386934,-0.180922,-0.078003,0.111116,0.275643,-0.318659
4,0.574748,0.28833,0.414676,0.596384,0.288179,0.453933,0.49959,0.332577,0.483842,0.342445,0.162379,0.596171,0.486155,0.507599
5,-0.304903,-0.228659,0.43828,-0.0521876,-0.490895,0.132629,-0.152976,0.2387,-0.00693743,1.85118,0.573933,-0.0520342,-0.27939,0.0902487
6,-0.311082,-0.197874,-0.196413,-0.234457,-0.18657,-0.0758699,-0.176043,-0.0740132,-0.154371,-0.146006,-0.227605,-0.234507,-0.223013,-0.209369

In [7]:
clu_nu_df = pd.DataFrame(cluster_nutrition)
# clu_nu_df[[0]]
clu_nu_df.to_csv('clusterNu_df.csv')

In [8]:
# c = ["Calories","Moisture","Protein","Saturated_fat","Carbohydrate","Dietary_fiber","Mg","Fe","Zn","VitaminA","VitaminB_group","Fatty_acid_S","Fatty_acid_M","Fatty_acid_P"]
# i = ['Cluster1','Cluster2','Cluster3','Cluster4','Cluster5','Cluster6','Cluster7']
# # clusterNu_df = pd.DataFrame(clu_nu_df,columns = c, index = i)
# clusterNu_df = pd.DataFrame(columns = c, index = i)
# clusterNu_df['Calories']=clu_nu_df[[0]]
# # for tt in c:
# #     n = 0
# #     clusterNu_df[tt]=clu_nu_df[[n]]
# #     n+=1

    
# clusterNu_df